.TH MOC 8 "22 september 2004" "Version 2.0.0" "music on console"

.SH NAME
MOC \- console audio player

.SH SYNOPSIS
.B mocp
[OPTIONS] [FILE]

.SH DESRIPTION

MOC is a console audio player with simple ncurses interface. It supports OGG,
wav, and MP3 formats. Just run mocp, go to some directory using menu and
press enter to start playing file, program will be playing automaticaly rest
of the files in the directory.

.SH OPTIONS

.TP
.I TODO
Write this :)

.SH FILES

.I ~/.moc/config

Configuration file of MOC. Format is very simple, to see how to use it,
look into example configuration file (config.example) distributed with the
program.

.SH BUGS

You can't seek when the decoder finished decoding and the sound you hear is
from the output buffer. This is a disadvantage of big output buffer.

.SH HOMEPAGE
http://moc.daper.net

.SH AUTHOR

Damian Pietras <daper@daper.net>
