.\" Start example.
.de EX
.  nr mE \\n(.f
.  nf
.  nh
.  ft CW
..
.
.\" End example.
.de EE
.  ft \\n(mE
.  fi
.  hy \\n(HY
..
.
.TH MOC 1 "25 December 2005" "Version 2.4.0" "Music On Console"
.ad l
.SH NAME
MOC \- Console audio player
.LP
.SH SYNOPSIS
\fBmocp\fR [\fIOPTIONS\fR] [\fIFILE\fR|\fIDIR\fR ...]
.LP
.SH DESCRIPTION
MOC is a console audio player with simple ncurses interface.  It supports
OGG, WAV, MP3 and other formats.  Just run \fBmocp\fP, go to some directory
using the menu and press enter to start playing the file.  The program will
automatically play the rest of the files in the directory.
.LP
With no options and no file arguments the program begins in current
directory, or in \fBMusicDir\fP if the \fBStartInMusicDir\fP option is set
in the configuration file.  If you give a directory on the command line,
MOC will try to go there.  If a playlist is given, then it is loaded.
With multiple files, playlists or directories, everything will be added to
the playlist recursively (including the contents of any playlist given).
(Note that relative paths in playlists are resolved with respect to the
directory of the playlist, or of the symlink being used to reference it.)
.LP
.SH OPTIONS
If an option can also be set in the configuration file the command line
overrides it (but see the \fB\-O\fP option for the list-valued
configuration options exception).
.LP
.TP
\fB\-D\fP, \fB\-\-debug\fP
Run MOC in debug mode.  The client and server log a lot of information
to debug files.  Don't use this; the server log is large.  This is only
available if MOC was compiled without \fB\-\-disable\-debug\fP.
.LP
.TP
\fB\-S\fP, \fB\-\-server\fP
Run only the server and exit.
.LP
.TP
\fB\-F\fP, \fB\-\-foreground\fP
Implies \fB\-S\fP.  Run the server in foreground and log everything to stdout.
.LP
.TP
\fB\-R\fP \fINAME\fP[\fB:\fP...], \
\fB\-\-sound\-driver\fP \fINAME\fP[\fB:\fP...]
Use the specified sound driver(s).  They can be \fBOSS\fP, \fBALSA\fP,
\fBJACK\fP, \fBSNDIO\fP or \fBnull\fP (for debugging).  Some of the drivers
may not have been compiled in.  This option is called \fBSoundDriver\fP in
the configuration file.
.LP
.TP
\fB\-m\fP, \fB\-\-music\-dir\fP
Start in \fBMusicDir\fP (set in the configuration file).  This can be also
set in the configuration file as \fBStartInMusicDir\fP.
.LP
.TP
\fB\-a\fP, \fB\-\-append\fP
Append files, directories (recursively) and playlists given after command
line options to the playlist.  Don't start the interface.
.LP
.TP
\fB\-c\fP, \fB\-\-clear\fP
Clear the playlist.
.LP
.TP
\fB\-p\fP, \fB\-\-play\fP
Start playing from the first item on the playlist.
.LP
.TP
\fB\-f\fP, \fB\-\-next\fP
Request playing the next song from the server's playlist.
.LP
.TP
\fB\-r\fP, \fB\-\-previous\fP
Request playing the previous song from the server's playlist.
.LP
.TP
\fB\-s\fP, \fB\-\-stop\fP
Request the server to stop playing.
.LP
.TP
\fB\-x\fP, \fB\-\-exit\fP
Bring down the server.
.LP
.TP
\fB\-P\fP, \fB\-\-pause\fP
Request the server to pause playing.
.LP
.TP
\fB\-U\fP, \fB\-\-unpause\fP
Request the server to resume playing when paused.
.LP
.TP
\fB\-G\fP, \fB\-\-toggle\-pause\fP
Toggle between play and pause.
.LP
.TP
\fB\-k\fP [\fB+\fP|\fB\-\fP]\fIN\fP, \
\fB\-\-seek \fP[\fB+\fP|\fB\-\fP]\fIN\fP
Seek forward (positive) or backward (negative) by \fIN\fP seconds in the
file currently being played.
.LP
.TP
\fB\-T\fP \fITHEME\fP, \fB\-\-theme\fP \fITHEME\fP
Use a theme file.  If the path is not absolute, the file will be searched
for in \fB/usr/share/moc/themes/\fP (depends on installation prefix),
\fB~/.moc/themes/\fP and the current directory.
.LP
.TP
\fB\-C\fP \fIFILE\fP, \fB\-\-config\fP \fIFILE\fP
Use the specified configuration file instead of the default.  As this
file can specify commands which invoke other applications MOC will refuse
to start if it is not owned by either root or the current user, or if it is
writable by anyone other than it's owner.
.LP
.TP
\fB\-O\fP \fINAME\fP[\fB+\fP]\fB=\fP\fIVALUE\fP, \
\fB\-\-set\-option\fP \fINAME\fP[\fB+\fP]\fB=\fP\fIVALUE\fP
Override configuration option NAME with VALUE.  This option can be
repeated as many times as needed and the option name is not case sensitive.
Most option values are set before the configuration file is processed (which
allows the new values to be picked up by substitutions); however, list-valued
options are overridden afterwards (which gives the choice of whether the
configured values are replaced or added to).
.IP
See the example configuration file (\fBconfig.example\fP) for a description
of the options available.
.LP
.RS
.EX
Examples: \fB\-O AutoNext=no\fP
          \fB\-O messagelingertime=1 \-O XTerms+=xxt:xwt\fP
.EE
.RE
.IP
Note that MOC does not perform variable substitution as it does for values
read from the configuration file.
.LP
.TP
\fB\-M\fP \fIDIR\fP, \fB\-\-moc\-dir\fP \fIDIR\fP
Use the specified MOC directory instead of the default.  This also causes
the configuration file from that directory to be used.  This can also be
specified in the configuration file using the \fBMOCDir\fP option.
.LP
.TP
\fB\-y\fP, \fB\-\-sync\fP
This copy of the interface will synchronize its playlist with other clients.
This option is called \fBSyncPlaylist\fP in the configuration file.
.LP
.TP
\fB\-n\fP, \fB\-\-nosync\fP
This copy of the interface will not synchronize its playlist with other
clients (see above).
.LP
.TP
\fB\-A\fP, \fB\-\-ascii\fP
Use ASCII characters to draw lines.  (This helps on some terminals.)
.LP
.TP
\fB\-i\fP, \fB\-\-info\fP
Print the information about the file currently being played.
.LP
.TP
\fB\-Q\fP \fIFORMAT_STRING\fP, \fB\-\-format\fP \fIFORMAT_STRING\fP
Print information about the file currently being played using a format
string.  Replace string sequences with the actual information:
.IP
.RS 16
.EX
\fB%state\fP     State
\fB%file\fP      File
\fB%title\fP     Title
\fB%artist\fP    Artist
\fB%song\fP      SongTitle
\fB%album\fP     Album
\fB%tt\fP        TotalTime
\fB%tl\fP        TimeLeft
\fB%ts\fP        TotalSec
\fB%ct\fP        CurrentTime
\fB%cs\fP        CurrentSec
\fB%b\fP         Bitrate
\fB%r\fP         Rate
.EE
.RE
.IP
It is also possible to use variables from the \fBFormatString\fP
configuration file option.
.LP
.TP
\fB\-e\fP, \fB\-\-recursively\fP
Alias of \fB\-a\fP for backward compatibility.
.LP
.TP
\fB\-h\fP, \fB\-\-help\fP
Print a list of options with short descriptions and exit.
.LP
.TP
\fB\-V\fP, \fB\-\-version\fP
Print the program version and exit.
.LP
.TP
\fB\-v\fP [\fB+\fP|\fB\-\fP]\fIN\fP, \
\fB\-\-volume\fP [\fB+\fP|\fB\-\fP]\fIN\fP
Adjust the mixer volume.  You can set (\fB\-v 50\fP) or adjust
(\fB\-v +10\fP, \fB\-v \-10\fP).
.LP
.TP
\fB\-t\fP \fIOPTION\fP[\fB,\fP...], \fB\-\-toggle\fP \fIOPTION\fP[\fB,\fP...]
.TQ
\fB\-o\fP \fIOPTION\fP[\fB,\fP...], \fB\-\-on\fP \fIOPTION\fP[\fB,\fP...]
.TQ
\fB\-u\fP \fIOPTION\fP[\fB,\fP...], \fB\-\-off\fP \fIOPTION\fP[\fB,\fP...]
Followed by a list of identifiers, these will control MOC's playlist
options.  Valid identifiers are \fBshuffle\fP, \fBrepeat\fP and \fBautonext\fP.
They can be shortened to '\fBs\fP', '\fBr\fP' and '\fBn\fP' respectively.
.LP
.RS
.EX
Example: \fB\-t shuffle,r,n\fP
.EE
         would toggle shuffle, repeat and autonext all at once.
.RE
.LP
.TP
\fB\-j\fP \fIN\fP{\fBs\fP|\fB%\fP}, \fB\-\-jump\fP \fIN\fP{\fBs\fP|\fB%\fP}
Jump to some position in the current file.  \fIN\fP is the number of seconds
(when followed by an '\fBs\fP') or the percent of total file time (when
followed by a '\fB%\fP').
.LP
.RS
.EX
Examples: \fB\-j 10s\fP, \fB\-j 50%\fP
.EE
.RE
.LP
.SH FILES
.TP
.B ~/.moc
MOC directory for the configuration file, socket, the pid file and other data.
.LP
.TP
.B ~/.moc/config
Configuration file for MOC.  The format is very simple; to see how to use
it look at the example configuration file (\fBconfig.example\fP) distributed
with the program.  The example file fully describes all the configuration
options, and so is a useful reference when using the \fB\-O\fP option.  As
this file can specify commands which invoke other applications MOC will
refuse to start if it is not owned by either root or the current user, or if
it is writable by anyone other than it's owner.
.LP
.TP
.B ~/.moc/themes
.TQ
.B /usr/share/moc/themes
Default directories for the theme files.
.LP
.TP
.B /usr/share/moc/decoder_plugins
Default directories for the audio decoder plugins.
.LP
.TP
.B mocp_client_log
.TQ
.B mocp_server_log
Client and server log files.  These files are created in the directory in
which the client and server are started.  (Also see the \fB\-D\fP option.)
.LP
.SH BUGS
Command line options that affect the server behaviour (like
\fB\-\-sound\-driver\fP) are ignored if the server is already running at
the time of executing \fBmocp\fP.  The user is not warned about this.
.LP
.SH HOMEPAGE
http://moc.daper.net/
.LP
.SH AUTHOR
Damian Pietras     <daper@daper.net>
.br
MOC Maintainer(s)  <mocmaint@daper.net>
